/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package ecommerce

import kotlin.test.Test
import org.springframework.modulith.core.ApplicationModules;

class AppTest {
    @Test fun verifyStructure() {
        ApplicationModules.of(Application::class.java).verify()
    }
}
